FROM python:3.5-slim

# RUN apt-get update && apt-get install libgtk2.0-dev -y

COPY . /app
WORKDIR /app

RUN apt-get update && apt-get install libgtk2.0-dev -y
# Устанавливаем все зависимости
RUN python3 -m pip install -r requirements.txt
# Запускаем приложение
ENTRYPOINT ["python3"]
CMD ["scripts/main.py"]
